version: '3.9'

services:
  app:
    build: .
    container_name: ai_recipe_parser
    ports:
      - "8501:8501"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
